name: Ejemplo contextos

on:
  pull_request:
    types: 
     - labeled
     - unlabeled

env:
  mi_nombre: Cristian


jobs:
  mostrar-contextos-1:
    #if: ${{ github.ref != 'refs/heads/develop' }}
    #if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: chechout
        uses: actions/checkout@v5
      - name: Mostrar branch
        run: echo "La rama es ${{ github.ref }}"
      - name: Mostrar repo
        run: echo "El repo es ${{ github.repository }}"
      - name: Mostrar nombre
        run: echo "MI nombre es $mi_nombre"
        #env:
          #mi_nombre: Cristian


  mostrar-contextos-2:
    needs: mostrar-contextos-1
    #if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: mostrar variable
        run: echo "mi nombre es $mi_nombre"
